openapi: 3.0.3
info:
  title: Bank Argent API documentation
  version: 1.1.0
  description: Transaction Module of the Bank Arget API documentation. This deliverable is part of the Project 013 - Utilisez une API pour un compte utilisateur bancaire avec React of the Développeur d'application - JavaScript React path with OpenClassrooms.
  contact: 
    name: kidereo
    url: https://github.com/kidereo/oc-p013-frontend
    
servers: 
  - url: http://localhost:3001/api/v1
    description: Backend server
 
paths:
  /accounts/{accountId}/transactions:
    get:
      description: Obtain a list of transactions on a certain account.
      summary: List transactions
      tags:
        - Transaction Module
      security: 
        - authToken: []
      parameters:
        - name: Authorisation
          required: true
          in: header
          description: Insert JWT token
          schema:
            type: string
            scheme: bearer
            bearerFormat: JWT
        - name: accountId
          in: path
          description: Account ID to which the retrieved transactions belong.
          required: true
          schema:
            type: integer
            example: 2
        - name: bodyLimit
          in: query
          description: Number of transactions returned
          schema:
            type: integer
            minimum: 5
            maximum: 50
            example: 6
      responses:
        200:
          description: Transactions retrieved sucessfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    transaction id:
                      type: integer
                      example: 506
                    transaction date:
                      type: string
                      example: June 20th, 2020
                    transaction description:
                      type: string
                      example: Golden Sun Bakery
                    transaction amount:
                      type: number
                      example: 500
                    account balance:
                      type: number
                      example: 2087.79
        401:
          description: Unauthorized.
        500:
          description: Internal Server Error.
        503:
          description: Service Unavailable.

  /accounts/{accountId}transactions/{transactionId}:
    get:
      description: Obtain details of an individual transaction on a certain account.
      summary: Detail a transaction
      tags:
        - Transaction Module
      security: 
        - authToken: []
      parameters:
        - name: Authorisation
          required: true
          in: header
          description: Insert JWT token
          schema:
            type: string
            scheme: bearer
            bearerFormat: JWT
        - name: accountId
          in: path
          description: Account ID to which the retrieved transaction belongs.
          required: true
          schema:
            type: integer
            example: 2
        - name: transactionId
          in: path
          description: Transaction ID for which detailes are retrieved.
          required: true
          schema:
            type: integer
            example: 40
      responses: 
        200:
          description: Transactions retrieved sucessfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    transaction id:
                      type: integer
                      example: 506
                    transaction date:
                      type: string
                      example: June 20th, 2020
                    transaction description:
                      type: string
                      example: Golden Sun Bakery
                    transaction amount:
                      type: number
                      example: 500
                    account balance:
                      type: number
                      example: 2087.79
                    transaction type:
                      type: string
                      example: Electronic
                    transaction category:
                      type: string
                      example: Food
                    transaction notes:
                      type: string
                      example: Baguette tradition
        401:
          description: Unauthorized.
        500:
          description: Internal Server Error.
        503:
          description: Service Unavailable.

    put:
      description: Modify a category and/or notes of the transaction.
      summary: Modify transaction details
      tags:
        - Transaction Module
      security: 
        - authToken: []
      parameters:
        - name: Authorisation
          required: true
          in: header
          description: Insert JWT token
          schema:
            type: string
            scheme: bearer
            bearerFormat: JWT
        - name: accountId
          in: path
          description: Account ID to which the retrieved transaction belongs.
          required: true
          schema:
            type: integer
            example: 2
        - name: transactionId
          in: path
          description: Transaction ID for which detailes are retrieved.
          required: true
          schema:
            type: integer
            example: 40
      requestBody: 
        required: true
        content: 
          application/json:
            schema: 
              type: object
              properties: 
                category:
                  type: string
                  example: Food
                notes: 
                  type: string
                  example: Baguette tradition
      responses: 
        200:
          description: Transaction details modified sucessfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 0
                  message:
                    type: string
                    example: Transaction details modified sucessfully
                  body:
                    type: object
                    properties: 
                      id:
                        type: string
                        example: 636bf01cdb04cc40b29ec821
                      email:
                        type: string
                        example: james@univex.co.uk
        401:
          description: Unauthorized.
        403:
          description: Forbidden.
        500:
          description: Internal Server Error.
        503:
          description: Service Unavailable.

    delete:
      description: Delete a category and/or notes of the transaction.
      summary: Delete transaction details
      tags:
        - Transaction Module
      security: 
        - authToken: []
      parameters:
        - name: Authorisation
          required: true
          in: header
          description: Insert JWT token
          schema:
            type: string
            scheme: bearer
            bearerFormat: JWT
        - name: accountId
          in: path
          description: Account ID to which the retrieved transaction belong.
          required: true
          schema:
            type: integer
            example: 2
        - name: transactionId
          in: path
          description: Transaction ID for which detailes are retrieved.
          required: true
          schema:
            type: integer
            example: 40
      requestBody: 
        required: true
        content: 
          application/json:
            schema: 
              type: object
              properties: 
                category:
                  type: string
                notes: 
                  type: string
      responses:
        200:
          description: Transaction details deleted sucessfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 0
                  message:
                    type: string
                    example: Transaction details deleted sucessfully
                  body:
                    type: object
                    properties: 
                      id:
                        type: string
                        example: 636bf01cdb04cc40b29ec821
                      email:
                        type: string
                        example: james@univex.co.uk
        401:
          description: Unauthorized.
        403:
          description: Forbidden.
        500:
          description: Internal Server Error.
        503:
          description: Service Unavailable.

components:
  securitySchemes:
    authToken:
      type: apiKey
      in: header
      name: Authorisation
